server:
  port: 9092

spring:
  # rabbit mq
  rabbitmq:
    host: 192.168.3.9
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    # 开启消息确认机制
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
          acknowledge-mode: manual