server:
  port: 9090

spring:
  # rabbit mq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /

# 校验策略的内容和顺序
filters: apikey,sign,template,mobile,ip,fee